apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgadmin1.fullname" . }}-pgadmin
  labels:
  {{- include "pgadmin1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pgadmin.type }}
  selector:
    app: pgadmin
  {{- include "pgadmin1.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.pgadmin.ports | toYaml | nindent 2 }}