apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin
          image: elestio/pgadmin:latest
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "postgres@postgres.com"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "postgres"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
spec:
  type: NodePort
  ports:
    - port: 5050
      targetPort: 80
  selector:
    app: pgadmin

