app:
  app:
    env:
      awsAccessKeyId: AKIAWH7AYUPPRZKGOLTI
      awsDefaultRegion: us-east-1
      awsSecretAccessKey: 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
      prodDbHostname: postgres
      prodDbName: postgres
      prodDbPassword: postgres
      prodDbUsername: postgres
    image:
      repository: tejumasha/mininode
      tag: latest
  ports:
  - nodePort: 30011
    port: 3000
    targetPort: 3000
  replicas: 1
  type: NodePort
kubernetesClusterDomain: cluster.local
