apiVersion: v1
kind: Service
metadata:
  name: {{ include "appchart1.fullname" . }}-app
  labels:
  {{- include "appchart1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.type }}
  selector:
    app: app
  {{- include "appchart1.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.app.ports | toYaml | nindent 2 }}