apiVersion: v1
kind: Service
metadata:
  name: {{ include "mychart.fullname" . }}-gadmin
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.gadmin.type }}
  selector:
    app: pgadmin
  {{- include "mychart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.gadmin.ports | toYaml | nindent 2 }}